package main

import (
	"bytes"
	"encoding/binary"
	"math/rand"
	"sort"
)

// FontResult holds the output of font randomization.
type FontResult struct {
	FontBytes []byte
	CharMap   *CharMap
}

// tblInfo holds a table's offset and length in the font binary.
type tblInfo struct{ offset, length uint32 }

// buildFont constructs a complete SFNT font from a map of table tag → bytes.
// Tables are sorted by tag, offsets are recalculated, and the head checksum
// is zeroed.
func buildFont(tables map[uint32][]byte) ([]byte, error) {
	tags := make([]uint32, 0, len(tables))
	for tag := range tables {
		tags = append(tags, tag)
	}
	sort.Slice(tags, func(i, j int) bool { return tags[i] < tags[j] })

	numTables := len(tags)
	headerSize := 12 + numTables*16

	// Calculate offsets with 4-byte padding
	offset := uint32(headerSize)
	offsets := make(map[uint32]uint32, numTables)
	for _, tag := range tags {
		offsets[tag] = offset
		paddedLen := uint32(len(tables[tag]))
		if paddedLen%4 != 0 {
			paddedLen += 4 - paddedLen%4
		}
		offset += paddedLen
	}

	out := make([]byte, offset)

	// Header
	binary.BigEndian.PutUint32(out[0:], 0x00010000) // TrueType
	binary.BigEndian.PutUint16(out[4:], uint16(numTables))
	sr := uint16(1)
	es := uint16(0)
	for sr*2 <= uint16(numTables) {
		sr *= 2
		es++
	}
	sr *= 16
	binary.BigEndian.PutUint16(out[6:], sr)
	binary.BigEndian.PutUint16(out[8:], es)
	binary.BigEndian.PutUint16(out[10:], uint16(numTables)*16-sr)

	// Directory entries
	for i, tag := range tags {
		base := 12 + i*16
		binary.BigEndian.PutUint32(out[base:], tag)
		binary.BigEndian.PutUint32(out[base+4:], 0) // checksum placeholder
		binary.BigEndian.PutUint32(out[base+8:], offsets[tag])
		binary.BigEndian.PutUint32(out[base+12:], uint32(len(tables[tag])))
	}

	// Table data
	for _, tag := range tags {
		copy(out[offsets[tag]:], tables[tag])
	}

	// Zero head checksum adjustment
	zeroHeadChecksumAdjustment(out, numTables)

	return out, nil
}

func zeroHeadChecksumAdjustment(font []byte, numTables int) {
	for i := 0; i < numTables; i++ {
		base := 12 + i*16
		tag := binary.BigEndian.Uint32(font[base : base+4])
		if tag == 0x68656164 {
			offset := binary.BigEndian.Uint32(font[base+8 : base+12])
			if offset+12 <= uint32(len(font)) {
				binary.BigEndian.PutUint32(font[offset+8:offset+12], 0)
			}
			return
		}
	}
}

// sanitizeNameTable replaces all identifying metadata in the font's name table
// with generic/randomized values. This removes references to the original font
// family name, designer, manufacturer, etc.
func sanitizeNameTable(nameBytes []byte, seed int64) []byte {
	if len(nameBytes) < 6 {
		return nameBytes
	}

	count := int(binary.BigEndian.Uint16(nameBytes[2:4]))
	stringOffset := int(binary.BigEndian.Uint16(nameBytes[4:6]))

	// Parse records
	type nameRecord struct {
		platformID uint16
		encodingID uint16
		languageID uint16
		nameID     uint16
		length     uint16
		offset     uint16
	}

	records := make([]nameRecord, count)
	for i := 0; i < count; i++ {
		base := 6 + i*12
		if base+12 > len(nameBytes) {
			break
		}
		records[i] = nameRecord{
			platformID: binary.BigEndian.Uint16(nameBytes[base:]),
			encodingID: binary.BigEndian.Uint16(nameBytes[base+2:]),
			languageID: binary.BigEndian.Uint16(nameBytes[base+4:]),
			nameID:     binary.BigEndian.Uint16(nameBytes[base+6:]),
			length:     binary.BigEndian.Uint16(nameBytes[base+8:]),
			offset:     binary.BigEndian.Uint16(nameBytes[base+10:]),
		}
	}

	rng := rand.New(rand.NewSource(seed))
	randomTag := func(n int) string {
		const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
		b := make([]byte, n)
		for i := range b {
			b[i] = chars[rng.Intn(len(chars))]
		}
		return string(b)
	}

	familyName := randomTag(8)

	// Replacement values for key nameIDs (Microsoft platform only)
	replacements := map[uint16]string{
		0:  "Generated by Scribble",
		1:  familyName,
		2:  "Regular",
		3:  familyName + "-Regular",
		4:  familyName + " Regular",
		5:  "Version 1.0",
		6:  familyName + "-Regular",
		7:  "",
		8:  "Scribble",
		9:  "Scribble",
		11: "",
		12: "",
		13: "",
		14: "",
		25: familyName,
	}

	// Build new records: only keep essential nameIDs, drop extended ones
	type newRecord struct {
		rec    nameRecord
		value  string
	}

	var newRecords []newRecord

	for _, rec := range records {
		// Skip extended nameIDs (256+) that are font-specific metadata
		if rec.nameID > 25 {
			continue
		}

		// Get the original string value
		strStart := stringOffset + int(rec.offset)
		strEnd := strStart + int(rec.length)
		if strEnd > len(nameBytes) {
			continue
		}

		var value string
		if rec.platformID == 3 && rec.encodingID == 1 {
			// Microsoft platform, BMP encoding — UTF-16BE
			raw := nameBytes[strStart:strEnd]
			var decoded []byte
			for j := 0; j+1 < len(raw); j += 2 {
				decoded = append(decoded, raw[j+1])
			}
			value = string(decoded)
		} else if rec.platformID == 1 && rec.encodingID == 0 {
			// Mac platform, Roman encoding — ASCII
			value = string(nameBytes[strStart:strEnd])
		} else {
			// Keep other encodings as-is
			newRecords = append(newRecords, newRecord{rec: rec, value: string(nameBytes[strStart:strEnd])})
			continue
		}

		// Replace identifying nameIDs
		if replacement, ok := replacements[rec.nameID]; ok {
			value = replacement
		}

		newRecords = append(newRecords, newRecord{rec: rec, value: value})
	}

	// Rebuild the name table binary
	var buf bytes.Buffer

	// Header
	binary.Write(&buf, binary.BigEndian, uint16(0))              // format
	binary.Write(&buf, binary.BigEndian, uint16(len(newRecords))) // count
	// stringOffset will be filled in later
	stringOffsetPos := buf.Len()
	buf.Write([]byte{0, 0}) // placeholder

	// Calculate string storage start
	headerLen := 6 + len(newRecords)*12

	// Build string data and write records
	type stringEntry struct {
		data []byte
	}
	var strings []stringEntry
	currentOffset := 0

	for _, nr := range newRecords {
		var data []byte
		if nr.rec.platformID == 3 && nr.rec.encodingID == 1 {
			// UTF-16BE encoding
			data = make([]byte, len(nr.value)*2)
			for i, r := range nr.value {
				data[i*2] = byte(r >> 8)
				data[i*2+1] = byte(r)
			}
		} else {
			data = []byte(nr.value)
		}

		// Write record
		binary.Write(&buf, binary.BigEndian, nr.rec.platformID)
		binary.Write(&buf, binary.BigEndian, nr.rec.encodingID)
		binary.Write(&buf, binary.BigEndian, nr.rec.languageID)
		binary.Write(&buf, binary.BigEndian, nr.rec.nameID)
		binary.Write(&buf, binary.BigEndian, uint16(len(data)))
		binary.Write(&buf, binary.BigEndian, uint16(currentOffset))

		strings = append(strings, stringEntry{data: data})
		currentOffset += len(data)
	}

	// Patch stringOffset
	binary.BigEndian.PutUint16(buf.Bytes()[stringOffsetPos:], uint16(headerLen))

	// Write string data
	for _, s := range strings {
		buf.Write(s.data)
	}

	return buf.Bytes()
}

func parseCmap(data []byte) map[rune]uint16 {
	result := make(map[rune]uint16)
	if len(data) < 4 {
		return result
	}
	numTables := int(uint16(data[2])<<8 | uint16(data[3]))
	offset := 4
	for i := 0; i < numTables && offset+8 <= len(data); i++ {
		platform := uint16(data[offset])<<8 | uint16(data[offset+1])
		encoding := uint16(data[offset+2])<<8 | uint16(data[offset+3])
		subOff := uint32(data[offset+4])<<24 | uint32(data[offset+5])<<16 |
			uint32(data[offset+6])<<8 | uint32(data[offset+7])
		if subOff+2 > uint32(len(data)) {
			offset += 8
			continue
		}
		format := uint16(data[subOff])<<8 | uint16(data[subOff+1])
		if platform == 3 && encoding == 1 && format == 4 {
			for k, v := range parseCmapFormat4(data[subOff:]) {
				result[k] = v
			}
		}
		if platform == 3 && encoding == 10 && format == 12 {
			for k, v := range parseCmapFormat12(data[subOff:]) {
				result[k] = v
			}
		}
		offset += 8
	}
	return result
}

func parseCmapFormat4(data []byte) map[rune]uint16 {
	result := make(map[rune]uint16)
	if len(data) < 14 {
		return result
	}
	segCount := int(uint16(data[6])<<8|uint16(data[7])) / 2
	if len(data) < 16+segCount*8 {
		return result
	}
	endCodes := make([]uint16, segCount)
	startCodes := make([]uint16, segCount)
	idDeltas := make([]int16, segCount)
	idRangeOffsets := make([]uint16, segCount)
	base := 14
	for i := 0; i < segCount; i++ {
		endCodes[i] = uint16(data[base+i*2])<<8 | uint16(data[base+i*2+1])
	}
	base += segCount*2 + 2
	for i := 0; i < segCount; i++ {
		startCodes[i] = uint16(data[base+i*2])<<8 | uint16(data[base+i*2+1])
	}
	base += segCount * 2
	for i := 0; i < segCount; i++ {
		idDeltas[i] = int16(uint16(data[base+i*2])<<8 | uint16(data[base+i*2+1]))
	}
	base += segCount * 2
	for i := 0; i < segCount; i++ {
		idRangeOffsets[i] = uint16(data[base+i*2])<<8 | uint16(data[base+i*2+1])
	}
	glyphIndexStart := base + segCount*2
	for i := 0; i < segCount-1; i++ {
		for c := int(startCodes[i]); c <= int(endCodes[i]); c++ {
			var glyphID uint16
			if idRangeOffsets[i] == 0 {
				glyphID = uint16((int(c) + int(idDeltas[i])) & 0xFFFF)
			} else {
				idx := glyphIndexStart + i*2 + int(idRangeOffsets[i]) + (c-int(startCodes[i]))*2
				if idx+2 <= len(data) {
					glyphID = uint16(data[idx])<<8 | uint16(data[idx+1])
					if glyphID != 0 {
						glyphID = uint16((int(glyphID) + int(idDeltas[i])) & 0xFFFF)
					}
				}
			}
			if glyphID != 0 {
				result[rune(c)] = glyphID
			}
		}
	}
	return result
}

func parseCmapFormat12(data []byte) map[rune]uint16 {
	result := make(map[rune]uint16)
	if len(data) < 16 {
		return result
	}
	nGroups := uint32(data[12])<<24 | uint32(data[13])<<16 | uint32(data[14])<<8 | uint32(data[15])
	if len(data) < 16+int(nGroups)*12 {
		return result
	}
	for i := uint32(0); i < nGroups; i++ {
		base := 16 + i*12
		startCharCode := rune(uint32(data[base])<<24 | uint32(data[base+1])<<16 | uint32(data[base+2])<<8 | uint32(data[base+3]))
		endCharCode := rune(uint32(data[base+4])<<24 | uint32(data[base+5])<<16 | uint32(data[base+6])<<8 | uint32(data[base+7]))
		startGlyphID := uint16(uint32(data[base+8])<<24 | uint32(data[base+9])<<16 | uint32(data[base+10])<<8 | uint32(data[base+11]))
		for c := startCharCode; c <= endCharCode; c++ {
			result[c] = startGlyphID + uint16(c-startCharCode)
		}
	}
	return result
}

func buildCmap4(mapping map[rune]uint16) []byte {
	if len(mapping) == 0 {
		return buildEmptyCmap()
	}
	type entry struct {
		codepoint rune
		glyphID   uint16
	}
	entries := make([]entry, 0, len(mapping))
	for c, g := range mapping {
		entries = append(entries, entry{c, g})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].codepoint < entries[j].codepoint })
	type segment struct {
		startCode uint16
		endCode   uint16
		glyphID   uint16
	}
	var segs []segment
	for _, e := range entries {
		cp := uint16(e.codepoint)
		if len(segs) > 0 {
			last := &segs[len(segs)-1]
			if cp == last.endCode+1 && e.glyphID == last.glyphID+(cp-last.startCode) {
				last.endCode = cp
				continue
			}
		}
		segs = append(segs, segment{startCode: cp, endCode: cp, glyphID: e.glyphID})
	}
	segs = append(segs, segment{startCode: 0xFFFF, endCode: 0xFFFF, glyphID: 0})
	segCount := len(segs)
	f4len := 14 + segCount*8 + 2
	f4 := make([]byte, f4len)
	binary.BigEndian.PutUint16(f4[0:], 4)
	binary.BigEndian.PutUint16(f4[2:], uint16(f4len))
	binary.BigEndian.PutUint16(f4[4:], 0)
	binary.BigEndian.PutUint16(f4[6:], uint16(segCount*2))
	sr := uint16(1)
	es := uint16(0)
	for sr*2 <= uint16(segCount) {
		sr *= 2
		es++
	}
	sr *= 2
	binary.BigEndian.PutUint16(f4[8:], sr)
	binary.BigEndian.PutUint16(f4[10:], es)
	binary.BigEndian.PutUint16(f4[12:], uint16(segCount)*2-sr)
	off := 14
	for _, seg := range segs {
		binary.BigEndian.PutUint16(f4[off:], seg.endCode)
		off += 2
	}
	off += 2
	for _, seg := range segs {
		binary.BigEndian.PutUint16(f4[off:], seg.startCode)
		off += 2
	}
	for _, seg := range segs {
		delta := int16(int(seg.glyphID) - int(seg.startCode))
		binary.BigEndian.PutUint16(f4[off:], uint16(delta))
		off += 2
	}
	for range segs {
		binary.BigEndian.PutUint16(f4[off:], 0)
		off += 2
	}
	hdrLen := 12
	buf := make([]byte, hdrLen+len(f4))
	binary.BigEndian.PutUint16(buf[0:], 0)
	binary.BigEndian.PutUint16(buf[2:], 1)
	binary.BigEndian.PutUint16(buf[4:], 3)
	binary.BigEndian.PutUint16(buf[6:], 1)
	binary.BigEndian.PutUint32(buf[8:], uint32(hdrLen))
	copy(buf[hdrLen:], f4)
	return buf
}

func buildEmptyCmap() []byte {
	f4len := 14 + 8 + 2
	f4 := make([]byte, f4len)
	binary.BigEndian.PutUint16(f4[0:], 4)
	binary.BigEndian.PutUint16(f4[2:], uint16(f4len))
	binary.BigEndian.PutUint16(f4[6:], 2)
	binary.BigEndian.PutUint16(f4[8:], 2)
	binary.BigEndian.PutUint16(f4[14:], 0xFFFF)
	binary.BigEndian.PutUint16(f4[18:], 0xFFFF)
	binary.BigEndian.PutUint16(f4[20:], 1)
	hdrLen := 12
	buf := make([]byte, hdrLen+f4len)
	binary.BigEndian.PutUint16(buf[2:], 1)
	binary.BigEndian.PutUint16(buf[4:], 3)
	binary.BigEndian.PutUint16(buf[6:], 1)
	binary.BigEndian.PutUint32(buf[8:], uint32(hdrLen))
	copy(buf[hdrLen:], f4)
	return buf
}

func GenerateFontKey() string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, 16)
	for i := range b {
		b[i] = chars[rand.Intn(len(chars))]
	}
	return string(b)
}

func buildRandomPostTable(numGlyphs int, seed int64) []byte {
	rng := rand.New(rand.NewSource(seed))

	namePool := make([]byte, 255)
	for i := range namePool {
		namePool[i] = byte(i + 1)
	}
	rng.Shuffle(len(namePool), func(i, j int) {
		namePool[i], namePool[j] = namePool[j], namePool[i]
	})

	nameIndices := make([]uint16, numGlyphs)
	for i := 0; i < numGlyphs; i++ {
		nameIndices[i] = uint16(258 + i)
	}

	nameStrings := make([]byte, numGlyphs*2)
	for i := 0; i < numGlyphs; i++ {
		nameStrings[i*2] = 1
		nameStrings[i*2+1] = namePool[i%len(namePool)]
	}

	headerSize := 32
	indicesSize := numGlyphs * 2
	totalSize := headerSize + 2 + indicesSize + len(nameStrings)

	buf := make([]byte, totalSize)
	binary.BigEndian.PutUint32(buf[0:], 0x00020000)
	binary.BigEndian.PutUint16(buf[8:], 0xFFFF)
	binary.BigEndian.PutUint16(buf[10:], 1)
	binary.BigEndian.PutUint16(buf[32:], uint16(numGlyphs))

	off := 34
	for _, idx := range nameIndices {
		binary.BigEndian.PutUint16(buf[off:], idx)
		off += 2
	}
	copy(buf[off:], nameStrings)

	return buf
}
